### PR TITLE
Cleaned up state machine and update to 2020

### PR DESCRIPTION
**Pull request by gahtzu**
-Cleaner + Faster state machine logic
-Added previous/incoming state parameter for subscription func delegate
-Removed idea of "state group" and old logic for isTransitional
-Added IsStateActive + GetCurrentState for helper funcs
-Minor cleanup in init logic

### CODE REVIEW

**Review by sbprogressive — CHANGES_REQUESTED** [review]
1) SHIT CODE! DO NOT MERGE!

2) Remove debug stuff:
-line 108 PocketPlayercontroller.cs
-line 550  PocketPlayercontroller.cs

3) Whitespace in line 10 PocketPlayerMachine.cs

**Comment by sbprogressive** [comment]
Also upgrade version

**Comment by sbprogressive** [comment]
@gahtzu PLEASE FIX!

**Comment by gahtzu** [comment]
made changes, merging

**Pull request merged**
